# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVnSjaVOH6mobGJoDIXQvZhC66F8SEE0
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

data = pd.read_csv('/content/drive/MyDrive/iot_ids_dataset.csv')
data.head()

print("Nombre de lignes et colonnes :")
print(data.shape)

print("\nInformations générales :")
print(data.info())

print("\nValeurs manquantes :")
print(data.isnull().sum())

data.describe()

print(data.dtypes)

print(data['Label'].value_counts())

plt.figure(figsize=(8,5))

sns.countplot(x='Label', data=data)

plt.title("Distribution des classes")

plt.xlabel("Classes")
plt.ylabel("Nombre")

plt.show()

plt.figure(figsize=(14,10))

sns.heatmap(
    data.corr(numeric_only=True),
    cmap='coolwarm',
    annot=False
)

plt.title("Matrice de corrélation")

plt.show()

data.hist(
    figsize=(18,15),
    bins=20
)
plt.suptitle("Distribution des variables")
plt.show()

plt.figure(figsize=(16,7))

sns.boxplot(data=data.select_dtypes(include=np.number))

plt.xticks(rotation=90)

plt.title("Détection des valeurs extrêmes")

plt.show()

sample_data = data.sample(300)
sns.pairplot(
    sample_data,
    hue='Label'
)
plt.show()

encoder = LabelEncoder()
data['Label'] = encoder.fit_transform(data['Label'])
print(data['Label'].head())

X = data.drop('Label', axis=1)
y = data['Label']

print("Variables d'entrée :")
print(X.head())

print("\nVariable cible :")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("Taille X_train :", X_train.shape)
print("Taille X_test :", X_test.shape)

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
print("Random Forest Accuracy :", rf_accuracy)

dt_model = DecisionTreeClassifier(
    random_state=42
)

dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)
print("Decision Tree Accuracy :", dt_accuracy)

lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_pred)
print("Logistic Regression Accuracy :", lr_accuracy)

knn_model = KNeighborsClassifier(
    n_neighbors=5
)

knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_pred)
print("KNN Accuracy :", knn_accuracy)

results = pd.DataFrame({
    'Algorithme': [
        'Random Forest',
        'Decision Tree',
        'Logistic Regression',
        'KNN'
    ],

    'Accuracy': [
        rf_accuracy,
        dt_accuracy,
        lr_accuracy,
        knn_accuracy
    ]
})

print(results)

plt.figure(figsize=(10,5))

sns.barplot(
    x='Algorithme',
    y='Accuracy',
    data=results
)

plt.title("Comparaison des algorithmes")
plt.ylim(0,1)
plt.show()

best_model = results.loc[
    results['Accuracy'].idxmax()
]

print("Meilleur modèle :")
print(best_model)

cm = confusion_matrix(y_test, rf_pred)

print(cm)

plt.figure(figsize=(7,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Prédictions")
plt.ylabel("Valeurs réelles")
plt.show()

report = classification_report(
    y_test,
    rf_pred
)
print(report)

importance = rf_model.feature_importances_
features = X.columns
importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': importance
})
importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)
print(importance_df)

plt.figure(figsize=(12,7))

plt.barh(
    importance_df['Feature'],
    importance_df['Importance']
)

plt.title("Importance des variables")
plt.xlabel("Importance")
plt.ylabel("Variables")
plt.show()

plt.figure(figsize=(12,5))
plt.plot(
    y_test.values[:100],
    label='Valeurs réelles'
)

plt.plot(
    rf_pred[:100],
    label='Prédictions'
)
plt.title("Comparaison Réel / Prédiction")
plt.legend()
plt.show()

sample = X_test.iloc[0:1]
prediction = rf_model.predict(sample)
print("Prédiction du modèle :", prediction)